version: '3.8'
services:
  gateway:
    image: ghcr.io/Kyomik/gatewayrealtime:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    # Jika butuh environment variable, tambahkan:
    # environment:
    #   - NODE_ENV=production
    #   - DATABASE_URL=postgresql://...
